application: rispennl
version: 1
runtime: python
api_version: 1

handlers:
- url: /images/(.*)
  static_files: static/images/\1
  upload: static/images/(.*)

- url: /css/(.*)
  static_files: static/css/\1
  upload: static/css/(.*)

- url: /js/(.*)
  static_files: static/js/\1
  upload: static/js/(.*)

- url: /
  script: main.py

- url: /json
  script: main.py

- url: /save
  script: main.py

- url: /delete
  script: main.py

- url: .*
  static_files: index.html
  upload: index\.html
