application: rispennl
version: 1
runtime: python
api_version: 1

handlers:
- url: /images/(.*)
  static_files: static/images/\1
  upload: static/images/(.*)

- url: .*
  static_files: index.html
  upload: index\.html

- url: /(json|save)
  script: main.py
